export { adminRoutes } from "./admin.routes.js";
export { adminCatalogRoutes } from "./admin.catalog.routes.js";
export { authRoutes } from "./auth.routes.js";
export { catalogRoutes } from "./catalog.routes.js";
export { chatRoutes } from "./chat.routes.js";
export { coverRoutes } from "./cover.routes.js";
export { libraryRoutes } from "./library.routes.js";
export { pageRoutes } from "./page.routes.js";
export { progressRoutes } from "./progress.routes.js";
